import './globals.css';
import type { Metadata } from 'next';
import ContactWrapper from './components/ContactWrapper';
import FooterClient from './components/FooterClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContactWrapper>
          {children}
          <FooterClient links={[]} />
        </ContactWrapper>
      </body>
    </html>
  );
}